# Allow for faster key repitition.
set -s escape-time 0

# Allow multiple commands to be entered without pressing the prefix key again in the specified time milliseconds (the default is 500).
set -sg repeat-time 600

# Because the 0 key is all the way on the other side...
set -g base-index 1
setw -g pane-base-index 1

setw -g automatic-rename on   # Rename window to reflect current program.
set -g renumber-windows on    # Renumber windows when a window is closed.
set -g set-titles on          # Set terminal title.

# Vim-style pane navigation.
bind h select-pane -L  # Move left.
bind j select-pane -D  # Move down.
bind k select-pane -U  # Move up.
bind l select-pane -R  # Move right.

# Pane resizing.
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

set-window-option -g mode-keys vi

# Use v to trigger selection.
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Use y to yank current selection.
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

